# Generated by Django 4.2.4 on 2023-12-02 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcardgameapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='deck',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='user',
        ),
        migrations.DeleteModel(
            name='WebImgs',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Deck',
        ),
    ]
