# Generated by Django 4.2.4 on 2023-11-14 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcardgameapp', '0002_deck_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='page_text',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='keywords',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='deck',
            old_name='cover_photo_text',
            new_name='description',
        ),
    ]
