# Generated by Django 4.2.4 on 2023-11-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcardgameapp', '0004_deck_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='category',
            field=models.CharField(choices=[('Science', 'Science'), ('Technology', 'Technology'), ('Engineering', 'Engineering'), ('Mathematics', 'Mathematics'), ('History', 'History'), ('Literature', 'Literature'), ('Languages', 'Languages'), ('Arts', 'Arts'), ('Health and Medicine', 'Health & Medicine'), ('Programming', 'Programming'), ('Misc', 'Misc.')], default='Misc', max_length=25),
        ),
    ]
