# Generated by Django 4.2.4 on 2023-11-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcardgameapp', '0006_contact_webimgs_user_profile_authentication_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='authentication_link',
            field=models.CharField(default='6u,(A*UNQ$;~Rip6Mg$!u5R^]A;\\i{', max_length=50, unique=True),
        ),
    ]
