# Generated by Django 4.2.4 on 2023-11-29 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcardgameapp', '0007_alter_user_profile_authentication_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='authentication_link',
            field=models.CharField(default='#7IuVhP<pN:5r72a8]rNpqJs1fWS]7', max_length=50, unique=True),
        ),
    ]
