# Generated by Django 4.2.4 on 2023-11-29 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcardgameapp', '0008_alter_user_profile_authentication_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='authentication_link',
            field=models.CharField(default='7219.-r2L836AzlRE^*RHVOn958219pdAQ&3it', max_length=50, unique=True),
        ),
    ]
