# Generated by Django 4.2.4 on 2023-11-29 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcardgameapp', '0009_alter_user_profile_authentication_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='authentication_link',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
